CREATE OR REPLACE TRIGGER TRG_EMP_SAL_RANGE
BEFORE INSERT OR UPDATE OF SALARY, JOB_ID ON EMPLOYEES
FOR EACH ROW
DECLARE
  v_min JOBS.MIN_SALARY%TYPE; v_max JOBS.MAX_SALARY%TYPE;
  v_job EMPLOYEES.JOB_ID%TYPE := NVL(:NEW.JOB_ID,:OLD.JOB_ID);
  v_sal EMPLOYEES.SALARY%TYPE := NVL(:NEW.SALARY,:OLD.SALARY);
BEGIN
  SELECT MIN_SALARY, MAX_SALARY INTO v_min, v_max FROM JOBS WHERE JOB_ID = v_job;
  IF v_sal < NVL(v_min,v_sal) OR v_sal > NVL(v_max,v_sal) THEN
    RAISE_APPLICATION_ERROR(-20040,'Salario fuera de rango para el puesto '||v_job);
  END IF;
END;
/